options:
  prev_tag: versio-prev

projects:
- name: setup-a-keyring-for-sops
  id: 1
  tag_prefix: ''
  labels: cargo
  version:
    file: Cargo.toml
    toml: package.version
  hooks:
    post_write: cargo fetch

sizes:
  major: ['!']
  minor: [feat]
  patch: [fix, docs, style, refactor, perf, test, chore, build, ci]
  none: []
  fail: ['*']
